const { useState, useEffect } = React;

const slides = [
  {
    id: "title",
    content: () => (
      <div className="title-slide">
        <div style={{fontSize: '80px', marginBottom: '2rem'}}>📊</div>
        <h1>Observability for SREs</h1>
        <p>Mastering Metrics, Logs & Traces on GCP & AWS</p>
        <div style={{marginTop: '2rem', display: 'flex', gap: '1rem'}}>
          <span className="tag tag-gcp">Google Cloud</span>
          <span className="tag tag-aws">AWS</span>
        </div>
      </div>
    )
  },
  {
    id: "pillars",
    content: () => (
      <div>
        <h2>The 3 Pillars of Observability</h2>
        <p style={{color: 'var(--text-muted)', marginBottom: '2rem'}}>Why it's more than just monitoring.</p>
        
        <div className="grid-2" style={{gridTemplateColumns: '1fr 1fr 1fr'}}>
          <div className="card">
            <div className="icon-box" style={{background: 'rgba(0, 163, 224, 0.2)', color: '#00A3E0'}}>
              <span style={{fontSize: '24px'}}>📈</span>
            </div>
            <h3>Metrics</h3>
            <p>Numeric data measured over intervals of time. (e.g. CPU Usage, Request Rate, Transfer Success Rate)</p>
          </div>
          <div className="card">
            <div className="icon-box" style={{background: 'rgba(0, 86, 157, 0.2)', color: '#00A3E0'}}>
              <span style={{fontSize: '24px'}}>💾</span>
            </div>
            <h3>Logs</h3>
            <p>Immutable, timestamped record of discrete events. Rich context but high volume. Used for deep debugging.</p>
          </div>
          <div className="card">
            <div className="icon-box" style={{background: 'rgba(0, 86, 157, 0.2)', color: '#00A3E0'}}>
              <span style={{fontSize: '24px'}}>📊</span>
            </div>
            <h3>Traces</h3>
            <p>A representation of a series of causally related distributed events. End-to-end flow across microservices.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: "log-journey-1",
    content: () => (
      <div>
        <h2>The Log Journey: Extraction</h2>
        <p style={{color: 'var(--text-muted)'}}>Step 1: Getting logs out of Kubernetes</p>
        
        <div className="flow-diagram">
          <div className="flow-node">Application Pod<br/><small>(Stdout/Stderr)</small></div>
          <div className="flow-arrow">→</div>
          <div className="flow-node">K8s Node<br/><small>(/var/log/containers/)</small></div>
          <div className="flow-arrow">→</div>
          <div className="flow-node" style={{borderColor: 'var(--accent-purple)'}}>DaemonSet<br/><small>(Fluent Bit/Fluentd/Promtail)</small></div>
        </div>

        <div className="grid-2" style={{marginTop: '2rem'}}>
          <div className="card">
            <h4>Why DaemonSet?</h4>
            <p>Ensures exactly one log collection agent runs on every single Kubernetes Node. It reads the local log files generated by all Pods on that Node.</p>
          </div>
          <div className="card">
            <h4>Data Enrichment</h4>
            <p>Fluent Bit automatically injects Kubernetes metadata (Namespace, Pod Name, Labels) into the raw log line before sending it forward.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: "log-journey-2",
    content: () => (
      <div>
        <h2>The Log Journey: Processing & Storage</h2>
        <p style={{color: 'var(--text-muted)'}}>Step 2: Routing logs to the right destination</p>
        
        <div className="flow-diagram">
          <div className="flow-node">DaemonSet</div>
          <div className="flow-arrow">→</div>
          <div className="flow-node">Kafka / Pub/Sub<br/><small>(Message Broker)</small></div>
          <div className="flow-arrow">→</div>
          <div className="flow-node">OpenTelemetry<br/>Collector</div>
          <div className="flow-arrow">→</div>
          <div className="flow-node" style={{borderColor: 'var(--gcp-color)'}}>Cloud Logging / S3<br/><small>(Cold/Hot Storage)</small></div>
        </div>

        <div className="grid-2" style={{marginTop: '2rem'}}>
          <div className="card">
            <h4>Why use Kafka or Pub/Sub?</h4>
            <p>Acts as a massive buffer. If the storage backend (Elasticsearch, GCP Logging) goes down or lags, the message broker prevents log loss and backpressure on the K8s cluster.</p>
          </div>
          <div className="card">
            <h4>OpenTelemetry (OTel) Collector</h4>
            <p>A vendor-agnostic way to receive, process (filter, scrub sensitive PII data), and export telemetry data to one or multiple destinations simultaneously.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: "ecosystem",
    content: () => (
      <div>
        <h2>Observability Ecosystem</h2>
        <p style={{color: 'var(--text-muted)', marginBottom: '1.5rem'}}>Popular tools in the market and where they fit</p>
        
        <div className="grid-2">
          <div className="card">
            <h3 style={{color: 'var(--accent-blue)'}}>Open Source / CNCF</h3>
            <ul>
              <li><strong>Prometheus:</strong> The industry standard for Metrics collection (Pull-based).</li>
              <li><strong>Grafana:</strong> The ultimate Visualization layer. Connects to everything.</li>
              <li><strong>ELK / EFK Stack:</strong> (Elasticsearch, Logstash/Fluentd, Kibana) Heavyweight champion for Log analytics.</li>
              <li><strong>Jaeger / Tempo:</strong> Distributed Tracing backends.</li>
            </ul>
          </div>
          <div className="card">
            <h3 style={{color: '#93c5fd'}}>Commercial APMs</h3>
            <ul>
              <li><strong>Datadog:</strong> Best-in-class UX, out-of-the-box dashboards, incredibly easy to set up. Cost scales rapidly with log volume.</li>
              <li><strong>Dynatrace:</strong> Extremely deep APM instrumentation. Davis AI auto-detects root causes. Premium enterprise pricing.</li>
              <li><strong>New Relic / Splunk:</strong> Powerful analytics and log indexing. Great for massive scale enterprise search.</li>
            </ul>
          </div>
        </div>
      </div>
    )
  },
  {
    id: "banking-usecase",
    content: () => (
      <div>
        <h2>Banking App Use Case</h2>
        <p style={{color: 'var(--text-muted)', marginBottom: '1.5rem'}}>Features: Transfer, Pay, Top-up, Withdraw</p>
        
        <div className="card" style={{marginBottom: '1.5rem'}}>
          <h3 style={{display: 'flex', alignItems:'center', gap:'0.5rem'}}>⚠️ Scenario: "Transfer Failed or Spinning Loader"</h3>
          <p>How we apply the 3 Pillars to solve a failed transaction:</p>
        </div>

        <div className="grid-2" style={{gridTemplateColumns: '1fr 1.5fr'}}>
          <div className="card">
            <h4>1. Log-based Metrics</h4>
            <p>We parse the raw JSON logs for <code>{"{ \"action\": \"transfer\", \"status\": \"failed\" }"}</code>. This generates a metric. Grafana sees a spike in failure rate and triggers a Discord Alert.</p>
          </div>
          <div className="card">
            <h4>2. Traces & Logs Working Together</h4>
            <p>The SRE clicks the alert and gets a <strong>Trace ID</strong> (e.g. <code>txn-8f92a</code>). They search this Trace ID in Cloud Logging or Datadog.</p>
            <p style={{marginTop: '0.5rem', paddingLeft: '1rem', borderLeft: '2px solid var(--accent-blue)'}}>
              <small>
                <strong>Hop 1:</strong> Mobile API Gateway (OK)<br/>
                <strong>Hop 2:</strong> Auth Service (OK)<br/>
                <strong>Hop 3:</strong> Core Banking DB (Timeout after 5s) ❌
              </small>
            </p>
            <p style={{marginTop: '0.5rem'}}><em>Result:</em> Root cause found in seconds without reading millions of unrelated logs.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: "grafana",
    content: () => (
      <div>
        <h2>Grafana & Alerting (Part 2)</h2>
        <p style={{color: 'var(--text-muted)'}}>Connecting the dots for actionable insights.</p>
        
        <div className="grid-2" style={{marginTop: '2rem'}}>
          <div className="card">
            <div className="icon-box" style={{background: 'rgba(244, 122, 32, 0.2)', color: '#F47A20'}}>
              <span style={{fontSize: '24px'}}>📈</span>
            </div>
            <h3>1. Grafana Dashboards</h3>
            <p>Connect to Prometheus or CloudWatch. Build a dashboard specifically for the Banking App (e.g. Success vs Failure rate for Top-ups).</p>
          </div>
          
          <div className="card">
            <div className="icon-box" style={{background: 'rgba(239, 68, 68, 0.2)', color: '#ef4444'}}>
              <span style={{fontSize: '24px'}}>⚠️</span>
            </div>
            <h3>2. Thresholds & Alerts</h3>
            <p>Set a rule: <code>avg(transfer_latency) &gt; 2s</code> for 5 minutes. If breached, trigger an Alarm state.</p>
          </div>
          
          <div className="card" style={{gridColumn: '1 / -1'}}>
            <div className="icon-box" style={{background: 'rgba(88, 101, 242, 0.2)', color: '#5865F2'}}>
              <span style={{fontSize: '24px'}}>🔔</span>
            </div>
            <h3>3. Discord Integration</h3>
            <p>Setup a Contact Point in Grafana using a Discord Webhook URL. Alerts instantly ping the #sre-alerts channel with context and a link to the dashboard.</p>
          </div>
        </div>
      </div>
    )
  }
];

function App() {
  const [currentSlide, setCurrentSlide] = useState(0);

  const nextSlide = () => {
    if (currentSlide < slides.length - 1) setCurrentSlide(c => c + 1);
  };

  const prevSlide = () => {
    if (currentSlide > 0) setCurrentSlide(c => c - 1);
  };

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'ArrowRight') nextSlide();
      if (e.key === 'ArrowLeft') prevSlide();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [currentSlide]);

  const progress = ((currentSlide + 1) / slides.length) * 100;

  return (
    <div className="presentation-container">
      <div className="progress-bar-container">
        <div className="progress-bar" style={{ width: \`\${progress}%\` }}></div>
      </div>
      
      <div className="slide-content">
        {slides[currentSlide].content()}
      </div>

      <div className="controls">
        <span style={{color: 'var(--text-muted)'}}>
          Slide {currentSlide + 1} of {slides.length}
        </span>
        <div style={{display: 'flex', gap: '1rem'}}>
          <button className="btn" onClick={prevSlide} disabled={currentSlide === 0}>
            ◀️ Prev
          </button>
          <button className="btn btn-primary" onClick={nextSlide} disabled={currentSlide === slides.length - 1}>
            Next ▶️
          </button>
        </div>
      </div>
    </div>
  );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);
